namespace clientlib
{
    delegate Windows.Foundation.IAsyncAction StoppedHandler();
    delegate Windows.Foundation.IAsyncAction ParsedHandler(Int32 queryId);
    delegate Windows.Foundation.IAsyncAction FetchedHandler(Windows.Data.Json.JsonObject fetched);
    delegate Windows.Foundation.IAsyncAction ErrorHandler(String message);

    [default_interface]
    runtimeclass Connection
    {
        Connection(Boolean useDefaultProfile);
        Windows.Foundation.IAsyncAction Shutdown(
            StoppedHandler onStopped, ErrorHandler onError);

        Windows.Foundation.IAsyncAction ParseQuery(String query,
            ParsedHandler onParsed, ErrorHandler onError);
        Windows.Foundation.IAsyncAction DiscardQuery(Int32 queryId);

        Windows.Foundation.IAsyncAction FetchQuery(Int32 queryId, String operationName, Windows.Data.Json.JsonObject variables,
            FetchedHandler onNext, FetchedHandler onComplete, ErrorHandler onError);
        Windows.Foundation.IAsyncAction Unsubscribe(Int32 queryId);
    }
}
